server:
  port: 7777

logging:
  file:
    path: logs
    name: mylog.log

spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/19lou?useUnicode=true&characterEncoding=utf8
    username: root
    password: jk88866512

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*
